### ISSUE TITLE
No backward compability after updating to 5.0.0-rc.8

### ISSUE THREAD

**Issue by wojtek1150** [angular/angularfire2#1659]
### Version info

**Angular:** 5.2.9

**Firebase:** 4.11.0

**AngularFire:** 5.0.0-rc.8

### How to reproduce these conditions

Failing prod build

### Debug output

> ERROR in Error during template compile of 'AppModule' Function calls are not supported in decorators but 'AngularFireModule' was called.
node_modules/angularfire2/auth/auth.d.ts(2,27): error TS2305: Module '"/workspace/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
node_modules/angularfire2/angularfire2.d.ts(3,27): error TS2305: Module '"/workspace/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
node_modules/angularfire2/firebase.app.module.d.ts(2,56): error TS2305: Module '"/workspace/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
node_modules/angularfire2/database/database.d.ts(4,27): error TS2305: Module '"/workspace/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.

**Comment by jamesdaniels** [comment]
Fixed in rc.9 which just went out.
