### ISSUE TITLE
New angularfire2 version 4.0.0-rc.1 : .take(1) on db.list fail

### ISSUE THREAD

**Issue by jamesamuel** [angular/angularfire2#1028]
@davideast   I upgraded my Angular 4 app to work in conjunction with angularfire2 4.0.0-rc.1 and have run into an issue when executing .take(1) on db.list. This worked fine in the previous version but not in v4. Any ideas?

`
this._db.list('$keygoeshere/clients').take(1)
        .subscribe(results => {
            this.clients = results
        })`

### Debug output
Error: Uncaught (in promise): TypeError: this._db.list(...).take is not a function
TypeError: this._db.list(...).take is not a function
    at ClientsListComponent.webpackJsonp.167.ClientsListComponent.ngOnInit

### Version info

**Angular:** 4.0.0

**Firebase:** 4.1.2

**AngularFire:** 4.0.0-rc.1

**Comment by davideast** [comment]
@jamesamuel Are you importing the operator?

```
import 'rxjs/add/operator/take';
```

**Comment by jamesamuel** [comment]
Thanks! One of those days!

p.s. you're the king 💪
