### ISSUE TITLE
Make AngularFire works with Firebase SDK 5.0.0

### ISSUE THREAD

**Issue by sarunint** [angular/angularfire2#1605]
### Version info

**Angular:** 6.0.0

**Firebase:** **5.0.0**

**AngularFire:** 5.0.0-rc.7

So, Firebase Javascript SDK 5.0.0 has been released. We should update AngularFire to be compatible with `firebase@5.0.0`.

**Comment by paulstelzer** [comment]
See #1607 Everything else is okay in angularfire2 with firebase@5.0.1

**Comment by JancoBH** [comment]
I get `changes.forEach is not a function` error with Firebase 5.0.0 or 5.0.1, with 4.13.0 there is not problem.

**Comment by paulstelzer** [comment]
@JancoBH Take a look at my PR  #1607 - docChanges is now a method, that's causing the error what i fixed in that PR

**Comment by JancoBH** [comment]
@paulstelzer thanks, im new with Git, I have to change it manually in my node_modules folder? or how can I implement it? I just saw the change in the [firebase js release note](https://firebase.google.com/support/release-notes/js)

**Comment by paulstelzer** [comment]
@JancoBH at the moment you have to manually change it in node_modules because angularfire2 does not have this change yet. As @hiepxanh said after angularfire2 releases a new version, you can update to the latest version
