### ISSUE TITLE
RXJS 6 compatibility

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angularfire2#1538]
### Version info

**Angular:** 6.0.0-rc.0

**Firebase:** 4.12.0

**AngularFire:** 5.0.0-rc.6

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

        "rxjs": "6.0.0-beta.3",
        "rxjs-compat": "6.0.0-beta.1",

### How to reproduce these conditions

`ng serve` fails with following error

```
ERROR in ./node_modules/angularfire2/database/observable/fromRef.js
Module not found: Error: Can't resolve 'rxjs/operator/observeOn' in 'C:\Development\profile-web\node_modules\angularfire2\database\observable'
```
in the `fromRef.js` file needs to be fixed import
`
import { observeOn } from 'rxjs/operator/observeOn';`
to
`import { observeOn } from 'rxjs/operators/observeOn';`

**Comment by patrickmichalina** [comment]
I actually think it would be `import { observeOn } from 'rxjs/operators`

**Comment by sconix** [comment]
Would be nice to get even some @next release for this. I can see that there was already changes made that removed the usage of observeOn so some sort of pre-release would allow us to start migrating to Angular 6.

**Comment by davideast** [comment]
We should have a next release soon.

**Comment by kylecordes** [comment]
Perhaps because of the RxJS version change, there seems to be a greater than usual level of activity around the Angular community aiming to have version 6 compatibility very close to the version 6 ship date. It would be great to see Angularfire2 come along for this ride.

**Comment by rurziceanu** [comment]
Hi
I see in npm version 5.0.0-rc.7.0-next published 4 days ago
After upgrading to angular 6 rc and rxjs 6, and  angularfire 5.0.0-rc.7.0-next I still have the errors in angularfire related to use of old rxjs functions

**Comment by GeorgeKnap** [comment]
@rurziceanu 
I think we have to wait for v6.next release.

**Comment by rurziceanu** [comment]
Is there release date for the v6.next? because angular v6 is now at release candidate 5.. and no angularfire2 package since now for v6.. all other dependencies are up to date.. :( 
I have only angularfire2 to migrate

**Comment by robertbaker** [comment]
rxjs just release 6.0 stable. They included a migration script to avoid the compat-layer.

**Comment by larssin** [comment]
I use the rxjs@5.6.0-forward-compat.4 to run the angularfire2@5.0.0-rc.6.0 and angular@6.0.0-rc.5 together.
See the Rxjs upgrade guide: https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/preview

**Comment by kylecordes** [comment]
@larssin That is quite interesting, it is the first suggestion I have seen (among many discussions!) to run Angular 6 with RxJS 5 forward-compat. This is a great workaround until Angularfire gets updated.

**Comment by ssrahul96** [comment]
update to RxJS 6 soon!

**Comment by rojasjandro89** [comment]
Any updates on this topic?? This renders AngularFire2 useless with the new version of angular

**Comment by GeorgeKnap** [comment]
@rojasjandro89 Temporary it works with `rxjs-compat` package and Angular 6. But yes, we are all eager for the new version.

**Comment by jamesdaniels** [comment]
Please stick with Firebase JS SDK 4.x for now, we're working on 5.0
compatibility but there are a number of breaking changes.

**Comment by jamesdaniels** [comment]
Fixed in `angularfire2@next`

**Comment by litchian18** [comment]
@jamesdaniels  Please look at @rojasjandro89  issue, I am facing the same issue, cant map to read firestore after update angular 6.

**Comment by yoni333** [comment]
angular 8 , rxjs 6.4 . angularfire 5.2.3 -  got ther error
ERROR in node_modules/rxjs/internal/symbol/observable.d.ts(4,18): error TS2687: All declarations of 'observable' must have identical modifiers.
