### ISSUE TITLE
Error in firebase.app.module.d.ts: Property 'performance' is missing in type 'FirebaseApp'

### ISSUE THREAD

**Issue by peterpeterparker** [angular/angularfire2#2059]
### Version info

angular/fire: 5.1.2
firebase: 5.11.0

### How to reproduce these conditions

`@angular/fire` v5.1.2 seems to doesn't play well with `firebase` v5.11.0. when these versions are installed I face the following error when I start my (Ionic) app:

```
[ng] ERROR in node_modules/@angular/fire/firebase.app.module.d.ts(17,22): error TS2420: Class 'FirebaseApp' incorrectly implements interface 'App'.
[ng]   Property 'performance' is missing in type 'FirebaseApp'.
```

Downgrading `firebase` to v5.10.1 fix the issue. I guess the property  'performance'  was added as a mandatory field in the last version of `firebase`.

**Comment by wh1terose** [comment]
Had this as well.  Downgrading'll fix it. Cheers

**Comment by cagcak** [comment]
ERROR in node_modules/@angular/fire/firebase.app.module.d.ts(17,22): error TS2420: Class 'FirebaseApp' incorrectly implements interface 'App'.
  Property 'performance' is missing in type 'FirebaseApp' but required in type 'App'.

**Comment by imanubhardwaj** [comment]
I'm also facing this issue, even used without ^ it stops working. Using it with Angular v7.
"@angular/fire": "^5.1.2",
"firebase": "^5.10.0"

**Comment by im-a-giraffe** [comment]
It worked for me using `"@angular/fire":` "^5.1.1"`and `"firebase": "5.10.1". Maybe you try that?
`

**Comment by imanubhardwaj** [comment]
> It worked for me using `"@angular/fire": "^5.1.1"`and `"firebase": "5.10.1".` Maybe you try that?
> `

Not working.

**Comment by GuilhermeLis** [comment]
> It worked for me using `"@angular/fire": "^5.1.1"`and `"firebase": "5.10.1".` Maybe you try that?
> `

I have to change in package.json and use the npm i... it doesn't clear to me

**Comment by jamesdaniels** [comment]
I just fixed this and cut 5.1.3

**Comment by peterpeterparker** [comment]
cool thx @jamesdaniels 👍

**Comment by peterpeterparker** [comment]
@jamesdaniels just noticed that there is no reference in the [CHANGELOG](https://github.com/angular/angularfire2/blob/master/CHANGELOG.md) about 5.1.3 ... on purpose or should I provide a PR to add a line about it (I guess the version contains only this fix right)?

**Comment by jbistis** [comment]
I need 5.9.2 for firebase.firestore.FieldValue.increment(1).  Does anyone have this working with newer versions of firebase?

**Comment by jbistis** [comment]
Working with 5.10.1. thanks..to monitranjan npm install --save firebase@5.10.1

**Comment by ReaperTech** [comment]
> I need 5.9.2 for firebase.firestore.FieldValue.increment(1). Does anyone have this working with newer versions of firebase?

yes I also need it to use increment()
