### ISSUE TITLE
Build fails on 5.0.0-rc.9

### ISSUE THREAD

**Issue by Metsuryu** [angular/angularfire2#1666]
### Version info

**Angular:**
@angular/core@5.0.5

**Firebase:**
firebase@4.10.1 

**AngularFire:**
angularfire2@5.0.0-rc.9 

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ubuntu 16.04.1 x64 
Node v6.14.2

### How to reproduce these conditions
The build failed on the Ubuntu server when the angularfire2 dependency was set as "~5.0.0-rc.4",
because it was downloading the rc.9 version, so I set it to "5.0.0-rc.7" (the last successful build), and it built normally, that leads me to believe there is a problem with the rc.9 version.

I decided to use the previous version after reading the errors below, since they were coming from "node_modules/angularfire2".

### Debug output

      01 ERROR in node_modules/angularfire2/auth/auth.d.ts(1,30): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/auth-types/index"' has no exported member 'IdTokenResult'.
      01 node_modules/angularfire2/auth/auth.d.ts(2,27): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
      01 node_modules/angularfire2/angularfire2.d.ts(3,27): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
      01 node_modules/angularfire2/firebase.app.module.d.ts(2,56): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
      01 node_modules/angularfire2/firebase.app.module.d.ts(8,35): error TS2307: Cannot find module '@firebase/functions-types'.
      01 node_modules/angularfire2/firestore/firestore.d.ts(4,27): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
      01 node_modules/angularfire2/database/database.d.ts(4,27): error TS2305: Module '"/root/Lantea/releases/20180516233308/node_modules/@firebase/app-types/index"' has no exported member 'FirebaseAppConfig'.
      01 src/app/global-functions.service.ts(1435,45): error TS2339: Property 'title' does not exist on type '{}'.
... And more errors about missing properties on objects.

### Expected behavior

Version 5.0.0-rc.7 builds successfully. I didn't test rc.8.

### Actual behavior

The build fails, and the above errors are given.

**Comment by jamesdaniels** [comment]
RC 9 only works with Firebase 5.0.2+

**Comment by bnayak0225** [comment]
https://github.com/bnayak0225/Biswajit-Note-Ionic-Firebase-angularfire2-5.0.0-rc-9 Here is my working project for IONIC and Angularfire2 5.0.0 rc-9
